### ISSUE TITLE
the camera is stuck in air

### ISSUE THREAD

**Issue by Alexplayrus2** [MaximumADHD/sm64-roblox#4]
so i decided to test what i just did with this and the camera seems to appear in the air, then i switch to server and my character is on the terrain like it should be
i havent added animations and sounds yet
a screenshot on how it looks to the client:
![image](https://user-images.githubusercontent.com/118437098/206416950-79952afb-e4d5-473c-b71f-264c645b618e.png)
a screenshot on how it looks to the server: 
![image](https://user-images.githubusercontent.com/118437098/206417473-c3babe3b-dae5-41a5-bdba-fac81c2f5843.png)

**Comment by Alexplayrus2** [comment]
> Any output?

no output except for "stack begin" and "stack end"

**Comment by SuperMarioYAHOOYAHOO** [comment]
having the same problem. is there a way to fix it?

**Comment by SuperMarioYAHOOYAHOO** [comment]
broken rbxl right here: https://drive.google.com/file/d/1Ikqn2VT0cN0zjwjysESesPoOk9FbyacF/view?usp=share_link

**Comment by H342u** [comment]
> Any output?

![image](https://user-images.githubusercontent.com/79845166/220211177-1909bf73-0d21-4e0d-8ad8-6bb8237e0482.png)

**Comment by H342u** [comment]
> Any output?

![image](https://user-images.githubusercontent.com/79845166/220211211-e517e52a-e18d-4e43-893c-8a72db796f16.png)
![image](https://user-images.githubusercontent.com/79845166/220211233-328b0561-833a-42da-87cd-bdb8f39c8617.png)

**Comment by tqoac** [comment]
The issue is because 'StarterPlayerScripts' is missing from 'StarterPlayer', opening a new file and copying the StarterPlayerScripts and pasting it into the StarterPlayer on your generated rbxl fixes the issue.

**Comment by Alexplayrus2** [comment]
> The issue is because 'StarterPlayerScripts' is missing from 'StarterPlayer', opening a new file and copying the StarterPlayerScripts and pasting it into the StarterPlayer on your generated rbxl fixes the issue.

gonna try it later, closing the issue for now on
