### ISSUE TITLE
How to make use of the .py files?

### ISSUE THREAD

**Issue by tqoac** [MaximumADHD/sm64-roblox#5]
![image](https://user-images.githubusercontent.com/51724932/224044018-a72bfab9-35fc-4a31-906a-409b2236afa0.png)
I've gotten this far, when starting `export_anims`.py, it starts going through animations, but when it runs `mass_exporter`.py, it errors.

@MaximumADHD

**Comment by tqoac** [comment]
![image](https://user-images.githubusercontent.com/51724932/223918335-9d6d8ff6-3f35-425e-b724-4ab181b60e01.png)
Its a start, when extract_anims.py opens mass_export.py it gives me that error.

**Comment by tqoac** [comment]
even when putting a z64 file in the same directory as the py file, nothing.
![image](https://user-images.githubusercontent.com/51724932/223919596-710764eb-853c-4360-9e98-8fd6be5d2377.png)

**Comment by tqoac** [comment]
![image](https://user-images.githubusercontent.com/51724932/223921907-1d7f0197-a453-4961-8d2a-558b377f0972.png)
started the py file via terminal

**Comment by tqoac** [comment]
Closing as i've done work on the py file and managed to get it to work.

**Comment by tqoac** [comment]
Closing as i've worked on the py file and got it to work, if anyone is reading, heres how i did it.

line 21: replace` sm64_level_parser.level_pointers` with `sm64_constants.level_pointers`
line 25: at the end of the function, add ", name" so it closes like this:
`sm64_anim.importAnimationToBlender(romfileSrc, animStart, mario_geo, segmentData, True, name)`

**Comment by tqoac** [comment]
In order to really import the animations, you have to have roblox internal, or you can import them painstakingly by hand.

**Comment by MaximumADHD** [comment]
I'll be interested to see if you actually get it importing correctly, but I hold no responsibility if N*ntendo does a DMCA takedown.

**Comment by tqoac** [comment]
> I'll be interested to see if you actually get it importing correctly, but I hold no responsibility if N*ntendo does a DMCA takedown.

Haha, almost! I've managed to get the animations going, however the character's LowerTorso doesn't move which leads to very weird animations. I think this has something to do with the rig I used, the one I used was off the fast64 github, I don't know if you modified yours in any way.

**Comment by SuperMarioYAHOOYAHOO** [comment]
> In order to really import the animations, you have to have roblox internal, or you can import them painstakingly by hand.

How do i get this "roblox internal"?
